"""
Design tokens for the app-wide Slate/Electric Blue desktop theme.

Central source for UI, chart, and report visual semantics.  Values are kept
here so page modules do not carry raw visual constants.
"""
# ---------------------------------------------------------------------------
# Semantic color tokens (factory desktop light theme)
# ---------------------------------------------------------------------------
# Primary / brand scale
PRIMARY_700 = "#1D4ED8"
PRIMARY_500 = "#2563EB"
PRIMARY_300 = "#93C5FD"
PRIMARY_100 = "#DBEAFE"

# Backgrounds / neutrals
BG_PRIMARY = "#F1F5F9"
BG_SECONDARY = "#F8FAFC"
BG_BLOCK = "#FFFFFF"
BG_PANEL = "#FFFFFF"
BG_CARD = "#FFFFFF"
SIDEBAR_DARK_BG = BG_PRIMARY
SIDEBAR_DARK_HOVER = "#E2E8F0"
SIDEBAR_TEXT_PRIMARY = "#0F172A"
SIDEBAR_TEXT_SECONDARY = "#475569"
SIDEBAR_ACCENT = PRIMARY_500
SIDEBAR_DIVIDER = "#CBD5E1"

# Surface states (buttons, tabs, list items)
SURFACE_HOVER = "#DBEAFE"
SURFACE_HOVER_SUBTLE = "#EFF6FF"
SURFACE_ACTIVE = "#BFDBFE"

# Text
TEXT_PRIMARY = "#0F172A"
TEXT_SECONDARY = "#475569"
TEXT_MUTED = "#52637A"
TEXT_DISABLED = "#94A3B8"
TEXT_ON_ACCENT = "#FFFFFF"  # text on primary/success/error buttons

# Accent / functional colors（B.3, C.）
# 稽核修正 B-01：ACCENT_SUCCESS/WARNING 調深以通過 WCAG AA 4.5:1（白底文字）
# 原版 #30D158 對比 2.87:1 → 修正 #1A9E3F 對比 5.1:1 ✅
# 原版 #FF9F0A 對比 2.82:1 → 修正 #B36800 對比 4.6:1 ✅
ACCENT_PRIMARY = PRIMARY_500
ACCENT_PRIMARY_HOVER = PRIMARY_700
ACCENT_SUCCESS       = "#166534"
ACCENT_SUCCESS_HOVER = "#14532D"
ACCENT_WARNING       = "#854D0E"
ACCENT_ERROR         = "#991B1B"
ACCENT_ERROR_HOVER   = "#7F1D1D"
# 圖表/非文字用途的鮮豔版（保持視覺活潑，對比要求較低）
ACCENT_SUCCESS_VIVID = "#16A34A"
ACCENT_WARNING_VIVID = "#D97706"
ACCENT_ERROR_VIVID   = "#DC2626"

# Border / divider
BORDER = "#CBD5E1"
BORDER_HOVER = "#94A3B8"
BORDER_SUBTLE = "#E2E8F0"

# Industrial semantic surfaces (low-saturation, non-decorative status tints)
INFO_SURFACE = PRIMARY_100
INFO_SURFACE_SUBTLE = SURFACE_HOVER_SUBTLE
SUCCESS_SURFACE = "#DCFCE7"
SUCCESS_SURFACE_SUBTLE = "#F0FDF4"
WARNING_SURFACE = "#FEF3C7"
WARNING_SURFACE_SUBTLE = "#FFFBEB"
ERROR_SURFACE = "#FEE2E2"
ERROR_SURFACE_SUBTLE = "#FEF2F2"
NEUTRAL_SURFACE = BG_SECONDARY

# ---------------------------------------------------------------------------
# Semantic state tokens (UI state design refactor: multi-signal, not color-only)
# ---------------------------------------------------------------------------
# Text by state
TEXT_STATE_ENABLED = TEXT_PRIMARY
TEXT_STATE_DISABLED = TEXT_MUTED
TEXT_STATE_INCOMPATIBLE = "#854D0E"
TEXT_STATE_SELECTED = TEXT_ON_ACCENT
TEXT_STATE_WARNING = ACCENT_WARNING
TEXT_STATE_ERROR = ACCENT_ERROR
TEXT_STATE_SUCCESS = ACCENT_SUCCESS
TEXT_STATE_INFO = TEXT_SECONDARY
# Background by state
BG_STATE_ENABLED = "transparent"
BG_STATE_DISABLED = BG_BLOCK
BG_STATE_SELECTED = SURFACE_ACTIVE
BG_STATE_INCOMPATIBLE = "#FEF9C3"
BG_STATE_HOVER = SURFACE_HOVER
# Border by state
BORDER_SELECTED = ACCENT_PRIMARY
BORDER_WARNING = ACCENT_WARNING
BORDER_ERROR = ACCENT_ERROR
BORDER_INCOMPATIBLE = "#FEF08A"
# Status bar lamp (idle=grey, loading=blue, warning=yellow, success=green, error=red)
STATUS_LAMP_IDLE = TEXT_MUTED
STATUS_LAMP_LOADING = PRIMARY_500
STATUS_LAMP_WARNING = ACCENT_WARNING
STATUS_LAMP_SUCCESS = ACCENT_SUCCESS
STATUS_LAMP_ERROR = ACCENT_ERROR
STATUS_LAMP_SIZE = 10  # Lamp circle diameter (px); border-radius = SIZE/2
CONN_LAMP_SIZE = 8     # Connection indicator lamp diameter (smaller than main lamp)

# Chart colors (SPC / capability) — single source for all chart series and limits
# Data series: primary series line/points (control chart, run chart, EWMA, etc.)
CHART_SERIES = "#2563EB"        # Data line & point
CHART_SERIES_SECONDARY = "#38BDF8"  # Secondary series (e.g. C-)
# Centerline / mean (CL, process mean)
CHART_CENTERLINE = "#16A34A"
# Control limits (UCL/LCL)
CHART_CONTROL_LIMITS = "#DC2626"
# Spec limits (USL/LSL) on distribution/capability views
CHART_SPEC_LIMITS = "#7C3AED"
# Out-of-control / anomaly points
CHART_OOC = "#DC2626"
# Histogram / bar fill (distribution, Pareto bars)
CHART_FILL = "#60A5FA"
# Grid / axes
CHART_GRID = "#E2E8F0"
CHART_GRID_MINOR = "#F1F5F9"
# Normal curve overlay
CHART_NORMAL_CURVE = ACCENT_PRIMARY
# Histogram bar edge (optional)
CHART_FILL_EDGE = BORDER
# Chart background layering (page vs plot-area)
CHART_FIGURE_BG = BG_SECONDARY
CHART_AXES_BG = BG_BLOCK
# Common chart annotation / accents
CHART_ANNOTATION = TEXT_SECONDARY
CHART_NEUTRAL_LINE = TEXT_MUTED
CHART_WARNING_MARK = ACCENT_WARNING
# Common bar colors by meaning
CHART_BAR_PASS = ACCENT_SUCCESS
CHART_BAR_FAIL = ACCENT_ERROR
CHART_BAR_NEUTRAL = CHART_FILL
# Feature palette (single source for 3-feature charts/tabs)
FEATURE_COLOR_HEIGHT = "#16A34A"
FEATURE_COLOR_AREA = "#F97316"
FEATURE_COLOR_VOLUME = "#2563EB"
FEATURE_COLORS = [FEATURE_COLOR_HEIGHT, FEATURE_COLOR_AREA, FEATURE_COLOR_VOLUME, "#7C3AED"]
FEATURE_TINT_HEIGHT = SUCCESS_SURFACE
FEATURE_TINT_AREA = "#FFEDD5"
FEATURE_TINT_VOLUME = PRIMARY_100
FEATURE_BORDER_HEIGHT = ACCENT_SUCCESS
FEATURE_BORDER_AREA = "#EA580C"
FEATURE_BORDER_VOLUME = PRIMARY_700
FEATURE_TOGGLE_MIN_HEIGHT = 40
FEATURE_TOGGLE_MIN_WIDTH = 0
# Marker sizes (實際使用視 chart 實作而定)
CHART_SERIES_MARKER_SIZE = 4
CHART_OOC_MARKER_SIZE = 7
CHART_LINE_STYLE_SECONDARY = "--"

# Chart typography (matplotlib fontsize, in pt) — 5-tier scale aligned with UI
CHART_FONT_TITLE = 11       # suptitle, ax.set_title
CHART_FONT_LABEL = 10       # ax.set_xlabel, ax.set_ylabel
CHART_FONT_LEGEND = 9       # ax.legend fontsize
CHART_FONT_TICK = 9         # tick label fontsize
CHART_FONT_ANNOTATION = 9   # limit annotations, stat overlays
CHART_FONT_MICRO = 8        # tiny annotations (limit values on multi-feature charts)
CHART_FONT_BASE = 11        # matplotlib rcParams["font.size"] default

# Scrollbar
SCROLLBAR_HANDLE = "#CBD5E1"
SCROLLBAR_HANDLE_HOVER = "#94A3B8"

# Table header — slightly distinct from white row bg for clear column header separation
TABLE_HEADER_BG = "#E2E8F0"

# Navigation phase header colors (color-coded flow stages)
NAV_PHASE_COLOR_PREPARE = "#2563EB"
NAV_PHASE_COLOR_ANALYZE = "#166534"
NAV_PHASE_COLOR_OUTPUT  = "#854D0E"

# Chart category colors (UI selectors, report checkbox groups, chart card accents)
CHART_GROUP_MONITOR_COLOR = PRIMARY_500
CHART_GROUP_MONITOR_BG = PRIMARY_100
CHART_GROUP_MONITOR_BORDER = PRIMARY_300
CHART_GROUP_CAPABILITY_COLOR = ACCENT_SUCCESS
CHART_GROUP_CAPABILITY_BG = SUCCESS_SURFACE
CHART_GROUP_CAPABILITY_BORDER = "#BBF7D0"
CHART_GROUP_ROOT_CAUSE_COLOR = ACCENT_ERROR
CHART_GROUP_ROOT_CAUSE_BG = ERROR_SURFACE
CHART_GROUP_ROOT_CAUSE_BORDER = "#FECACA"
CHART_GROUP_RELATION_COLOR = CHART_SPEC_LIMITS
CHART_GROUP_RELATION_BG = "#F3E8FF"
CHART_GROUP_RELATION_BORDER = "#DDD6FE"
CHART_GROUP_COMPARISON_COLOR = ACCENT_WARNING
CHART_GROUP_COMPARISON_BG = WARNING_SURFACE
CHART_GROUP_COMPARISON_BORDER = "#FDE68A"
CHART_GROUP_STYLE_KEY_BY_LABEL: dict[str, str] = {
    "製程監控": "monitor",
    "製程能力": "capability",
    "異常根源": "root-cause",
    "變數關係": "relation",
    "比較分析": "comparison",
}


def chart_group_style_key(group_label: str) -> str:
    """Return the stable QSS property value for a chart category label."""
    return CHART_GROUP_STYLE_KEY_BY_LABEL.get(group_label, "comparison")

# Navigation (left sidebar) — compact button height
NAV_STEP_BTN_HEIGHT = 28
NAV_STEP_BG = BG_BLOCK
NAV_STEP_TEXT = TEXT_PRIMARY
NAV_STEP_HOVER_BG = SURFACE_HOVER
NAV_STEP_SELECTED_BG = PRIMARY_100           # selected step background tint

# Refresh button secondary/outline tokens (visual hierarchy: refresh < next-step)
BTN_SECONDARY_BG = BG_BLOCK
BTN_SECONDARY_BORDER = ACCENT_PRIMARY
BTN_SECONDARY_TEXT = ACCENT_PRIMARY
BTN_SECONDARY_HOVER_BG = PRIMARY_100
BTN_SECONDARY_HOVER_BORDER = ACCENT_PRIMARY_HOVER
BTN_SECONDARY_HOVER_TEXT = ACCENT_PRIMARY_HOVER

# Spacing scale (px) — spec L-05: 4, 8, 12, 16, 20
SPACING_4 = 4
SPACING_8 = 8
SPACING_12 = 12
SPACING_16 = 16
SPACING_20 = 20
SPACING_24 = 24
SPACING_32 = 32

# Sub-scale (not in L-05 spec; used for fine-grained dense layout)
SPACING_XXS = 2
SPACING_XS = 6
SPACING_SM = 10

# Sidebar layout
SIDEBAR_GAP = 6
SIDEBAR_NAV_MIN_HEIGHT = 0
SIDEBAR_BUTTON_MIN_HEIGHT = 30
WORKFLOW_TAB_MIN_WIDTH = 120
# Brand header area (top of sidebar)
SIDEBAR_BRAND_HEIGHT = 40            # brand row min height (two-line: name + version)
SIDEBAR_BRAND_FONT_SIZE = 11
SIDEBAR_BRAND_VERSION_FONT_SIZE = 7.5
SIDEBAR_DIVIDER_HEIGHT = 1           # hairline divider between nav and control panel
SIDEBAR_CONTROL_MIN_WIDTH = 150
SIDEBAR_DB_TITLE_FONT_SIZE = 7.5
SIDEBAR_DB_BODY_FONT_SIZE = 7.0
SIDEBAR_DB_COUNT_FONT_SIZE = 6.5
SIDEBAR_DB_LIST_MAX_HEIGHT = 90
SIDEBAR_DB_BUTTON_HEIGHT = 20
SIDEBAR_DB_PANEL_SPACING = 3
SIDEBAR_DB_PANEL_MARGIN = 2
CONTROL_CONDITION_GROUP_MIN_HEIGHT = 120
CONTROL_STATUS_GROUP_MIN_HEIGHT = 140
CONTROL_STATUS_LINE_MIN_HEIGHT = 20
CONTROL_FORM_ROW_SPACING = 4
CONTROL_STATUS_SECTION_TOP_SPACING = 0
CONTROL_FORM_COL_SPACING = 6
SIDEBAR_COMPACT_INPUT_HEIGHT = 28
SIDEBAR_COMPACT_FEATURE_HEIGHT = 34
SIDEBAR_COMPACT_ACTION_HEIGHT = 32
SIDEBAR_CONDITIONS_COLLAPSE_HEIGHT = 720
CONTROL_DENSE_SECTION_TITLE_PT = 10.5
CONTROL_DENSE_FORM_LABEL_PT = 9
CONTROL_DENSE_STATUS_PT = 9
# Section title
GROUPBOX_TITLE_MARGIN_TOP = 26
GROUPBOX_TITLE_PADDING_TOP = 10

# 雙欄工程表單頁 (Two-column form page) layout pattern
PAGE_HEADER_BOTTOM_SPACING = 4
TWO_COLUMN_CONTENT_SPACING = 12
TWO_COLUMN_STRETCH_LEFT = 1
TWO_COLUMN_STRETCH_RIGHT = 1
TWO_COLUMN_MIN_COLUMN_WIDTH = 280
# 資料設定頁（DataSetupPage）響應式欄位
DATA_SETUP_BREAKPOINT_2COL = 980
DATA_SETUP_BREAKPOINT_3COL = 1080
# 三欄 stretch 權重
DATA_SETUP_COL_STRETCH_LEFT = 4
DATA_SETUP_COL_STRETCH_MID = 4
DATA_SETUP_COL_STRETCH_RIGHT = 3
PRIMARY_ACTION_TOP_SPACING = 10
LEFT_ALIGN_BUTTON_ROW_GAP = 12
CARD_SECTION_GAP = 16
PAGE_SECTION_GAP = 16
HEADER_ACTION_GAP = 12
HEADER_TOOLBAR_MIN_HEIGHT = 44
COMPACT_HEADER_TOOLBAR_MIN_HEIGHT = 32
COMPACT_HEADER_MARGIN_H = 8
COMPACT_HEADER_MARGIN_V = 4
TABLE_TOOLBAR_MARGIN_H = 8
TABLE_TOOLBAR_MARGIN_V = 4
TABLE_TOOLBAR_MIN_HEIGHT = 36
DATA_SETUP_PRIMARY_CARD_MIN_HEIGHT = 160
DATA_SETUP_SECONDARY_CARD_MIN_HEIGHT = 120
DATA_SETUP_PAGE_MARGIN_H = 12
DATA_SETUP_PAGE_MARGIN_V = 10
DATA_SETUP_COLUMN_GAP = 16
DATA_SETUP_TABLE_GAP = 8
DATA_SETUP_TABLE_LEFT_MIN_WIDTH = 360
DATA_SETUP_TABLE_RIGHT_MIN_WIDTH = 420
DATA_SETUP_TABLE_WORKORDER_MIN_HEIGHT = 110
DATA_SETUP_TABLE_SECTION_MIN_HEIGHT = 92
DATA_SETUP_TABLE_MAIN_MIN_HEIGHT = 330
DATA_SETUP_CARD_CONTENT_PADDING = 20
DATA_SETUP_CARD_SECTION_GAP = 16
DATA_SETUP_DENSE_STEP_TITLE_MIN_HEIGHT = 26
DATA_SETUP_DENSE_CAPTION_FONT_SIZE = 10.5
DATA_SETUP_DENSE_CAPTION_MIN_HEIGHT = 24
DATA_SETUP_DENSE_FORM_LABEL_FONT_SIZE = 11.5
DATA_SETUP_DENSE_FORM_LABEL_MIN_HEIGHT = 24
DATA_SETUP_DENSE_LIST_PADDING = 4
WORKORDER_CARD_MIN_HEIGHT = 360
COMPONENT_SUMMARY_KPI_MIN_HEIGHT = 0
DETAIL_CARD_MIN_HEIGHT = 84

# 高密度列表 / 表格行高
TABLE_ROW_MIN_HEIGHT = 32
DIAGNOSTIC_MATRIX_TABLE_MIN_HEIGHT = TABLE_ROW_MIN_HEIGHT * 8
DIAGNOSTIC_MATRIX_MIN_VISIBLE_ROWS = 1
DIAGNOSTIC_MATRIX_MAX_VISIBLE_ROWS = 8
DIAGNOSTIC_MATRIX_MAX_ROW_HEIGHT = 72
DIAGNOSTIC_MATRIX_TABLE_EXTRA_HEIGHT = 14
DIAGNOSTIC_MATRIX_MIN_SECTION_WIDTH = 72
DIAGNOSTIC_MATRIX_FEATURE_COL_WIDTH = 164
DIAGNOSTIC_MATRIX_CHART_COL_WIDTH = 220
DIAGNOSTIC_MATRIX_FAMILY_COL_WIDTH = 104
DIAGNOSTIC_MATRIX_STATUS_COL_WIDTH = 104
DIAGNOSTIC_MATRIX_DIMENSION_COL_WIDTH = 128
DIAGNOSTIC_MATRIX_VERDICT_COL_WIDTH = 164
DIAGNOSTIC_MATRIX_METRIC_COL_WIDTH = 252
DIAGNOSTIC_MATRIX_REASON_COL_WIDTH = 240
DIAGNOSTIC_MATRIX_EVIDENCE_DIM_COL_WIDTH = 104
DIAGNOSTIC_MATRIX_GAP_COUNT_COL_WIDTH = 64
DIAGNOSTIC_MATRIX_LINK_REASON_COL_WIDTH = 320

# 側欄內容緊湊版 padding
SIDEBAR_PADDING_COMPACT = 8

# Rail (收合軌)
RAIL_MARGIN_VERTICAL = 10
RAIL_SPACING = 8
RAIL_BTN_HEIGHT = 32
RAIL_BTN_HEIGHT_COLLAPSED = 28
RAIL_BTN_SIZE_OFFSET = 2
# Sidebar / rail widths
SIDEBAR_WIDTH_EXPANDED = 260
SIDEBAR_WIDTH_COLLAPSED = 56
SIDEBAR_WIDTH_MAX = 340       # H-03: hard cap — prevents sidebar from crowding workspace on drag
RAIL_WIDTH_EXPANDED = 24  # C-02: was 8 → toggle button was 6px wide (unclickable)
RAIL_WIDTH_COLLAPSED = 56
CHART_MAIN_MIN_HEIGHT = 420
CHART_SELECTOR_COMPACT_MAX_HEIGHT = 168
CHART_SELECTOR_CONTENT_MARGIN = 4
CHART_SELECTOR_GROUP_SPACING = 6
CHART_SELECTOR_CHECKBOX_MIN_HEIGHT = 22
CHART_SELECTOR_OPTION_COLUMNS = 2
CHART_CARD_HEADER_BUTTON_HEIGHT = 26
CHART_CARD_STATUS_MIN_HEIGHT = 20
ERROR_NO_DATA = "無有效資料可繪圖。"

# Chart compact description min height
CHART_DESC_MIN_HEIGHT = 20
# Recommendation chip strip fixed height
RECO_CHIP_STRIP_HEIGHT = 36
# Sidebar minimal buttons (collapsed rail) min height
SIDEBAR_MINIMAL_BTN_MIN_HEIGHT = 24
# Form combo box minimum width
FORM_COMBO_MIN_WIDTH = 200
DATA_SETUP_PRODUCT_COMBO_MIN_WIDTH = 312
DATA_SETUP_FIELD_MAX_WIDTH = 552
DATA_SETUP_NUMERIC_FIELD_MAX_WIDTH = 280
DATA_SETUP_PATH_ACTION_MIN_WIDTH = 160
DATA_SETUP_COMPACT_LABEL_WIDTH = 100
DATA_SETUP_COMPACT_PATH_MIN_WIDTH = 150
DATA_SETUP_COMPACT_META_LABEL_WIDTH = 80
DATA_SETUP_COMPACT_HINT_LABEL_WIDTH = 100
DATA_SETUP_WORKORDER_MIN_WIDTH = 120
DATA_SETUP_BATCH_INPUT_MIN_WIDTH = 100
DATA_SETUP_PASTE_TYPE_MIN_WIDTH = 80
DATA_SETUP_DROP_ZONE_MIN_HEIGHT = 52
DATA_SETUP_TABLE_LABEL_WIDTH = 170
DATA_SETUP_TABLE_ROW_MIN_HEIGHT = 32
DATA_SETUP_INLINE_LABEL_WIDTH = 88

# Radius（Linear/Notion 風格圓角，更現代）
RADIUS_SM = 4
RADIUS_MD = 6
RADIUS_BUTTON = 6
CARD_RADIUS = 8
CARD_PADDING = 20
BUTTON_MIN_HEIGHT = 30

# Interaction
FOCUS_RING_BORDER = ACCENT_PRIMARY
ELEVATION_SHADOW_MEDIUM = "rgba(17, 17, 17, 0.07)"
APPLE_GLASS_TINT = "rgba(255, 255, 255, 1.0)"
APPLE_GLASS_TINT_STRONG = "rgba(255, 255, 255, 1.0)"
APPLE_GLASS_BORDER = "rgba(229, 229, 234, 1.0)"
# Qt QSS 不支援 transition，保留供文件參考
TRANSITION_FAST_MS = 120
TRANSITION_NORMAL_MS = 180
BUTTON_PRESSED_SCALE = 0.98
BUTTON_DISABLED_OPACITY = 0.55

# Card shadow simulation tokens (Qt 無 box-shadow；用非對稱 border 模擬)
CARD_SHADOW_BOTTOM = BORDER_SUBTLE
CARD_SHADOW_BOTTOM_MD = BORDER

# Button gradient stops（扁平化 - 降低漸層幅度，更現代）
BTN_GRAD_LIGHT        = BG_BLOCK
BTN_PRIMARY_GRAD_LIGHT      = ACCENT_PRIMARY
BTN_PRIMARY_GRAD_HOVER_LIGHT = ACCENT_PRIMARY_HOVER
BTN_SUCCESS_GRAD_LIGHT      = ACCENT_SUCCESS
BTN_SUCCESS_GRAD_HOVER_LIGHT = ACCENT_SUCCESS_HOVER
BTN_ERROR_GRAD_LIGHT        = ACCENT_ERROR
BTN_ERROR_GRAD_HOVER_LIGHT  = ACCENT_ERROR_HOVER

# Size constants
COORD_REGISTRY_LIST_MAX_H  = 240
REFDES_SCROLL_MAX_H        = 400
CONFIDENCE_BAR_HEIGHT      = 8
RAIL_COLLAPSED_BTN_MARGIN  = 8
PATH_LABEL_ELIDE_MIN_W     = 60
EMPTY_COORD_SET            = "—"
EMPTY_MEAS_FILE            = "—"
PATH_LABEL_ELIDE_MARGIN    = 6
QT_MAX_WIDGET_DIM          = 16_777_215
FORM_GRID_ROW_SPACING      = CONTROL_FORM_ROW_SPACING - 2
IMR_HISTOGRAM_TAB_MIN_W    = 320
SEVERITY_LABEL_MIN_W       = 60
REFDES_SCROLL_MIN_H        = 200
DIAG_CONFIDENCE_LABEL_MIN_W = 80
ANALYSIS_BADGE_MIN_W        = 28
ANALYSIS_BADGE_MIN_H        = 22
FEATURE_BADGE_MIN_W         = 20
KPI_CARD_MIN_W              = 90
DATA_COL_SEPARATOR_W        = 1
SIDEBAR_TOGGLE_BTN_MIN_W    = 20
SIDEBAR_MINIMAL_BTN_MIN_W   = 36
SCROLLBAR_WIDTH             = 8
SCROLLBAR_RADIUS            = 4
SCROLLBAR_MIN_LENGTH        = 28
ACCENT_STRIPE_W             = 5
ACCENT_STRIPE_BLUE          = PRIMARY_500
ACCENT_STRIPE_RED           = ACCENT_ERROR
ACCENT_STRIPE_SUCCESS       = ACCENT_SUCCESS
CHECKBOX_INDICATOR_SIZE     = 18
COMBO_DROPDOWN_W            = 20
UI_DIVIDER_THICKNESS        = 1
STATUS_PROGRESS_BAR_HEIGHT  = 6
STATUS_PROGRESS_MIN_WIDTH   = 100
STATUS_PROGRESS_MAX_WIDTH   = 200
DIALOG_MIN_WIDTH_STANDARD        = 400
DIALOG_MIN_WIDTH_WIDE            = 480
DIALOG_MIN_HEIGHT_STANDARD       = 220
DIALOG_INTERPRETATION_INIT_WIDTH  = 900
DIALOG_INTERPRETATION_INIT_HEIGHT = 820
CHART_INTENT_SCROLL_HEIGHT  = 36
REPORT_INTENT_SCROLL_HEIGHT = 34
GROUP_ACTION_BUTTON_HEIGHT  = 22
SECONDARY_TAB_COMPACT_MIN_WIDTH = 72
SECONDARY_TAB_COMPACT_PADDING_H = 8
SECONDARY_TAB_COMPACT_PADDING_V = 2
STENCIL_NUMERIC_MIN_WIDTH   = 50
STENCIL_NUMERIC_MAX_WIDTH   = 70
STENCIL_ACTION_BUTTON_WIDTH = 100
STENCIL_LABEL_MIN_WIDTH     = 80
MEAS_LIB_PRODUCT_MIN_WIDTH  = 140
MEAS_LIB_WORKORDER_MIN_WIDTH = 110
MEAS_LIB_SHORT_FIELD_MIN_WIDTH = 90
MEAS_LIB_DATE_FIELD_MIN_WIDTH = 140
MEAS_LIB_WIDE_FIELD_MIN_WIDTH = 160
MEAS_LIB_ACTION_BUTTON_MIN_WIDTH = 124
MEAS_LIB_ACTION_BUTTON_MIN_HEIGHT = 34
MEAS_LIB_BUTTON_ROW_SPACING = 8
DIALOG_PPTX_CONFIRM_INIT_WIDTH = DIALOG_MIN_WIDTH_WIDE
DIALOG_PPTX_CONFIRM_INIT_HEIGHT = DIALOG_MIN_HEIGHT_STANDARD * 2
DIALOG_LIBRARY_EDIT_INIT_WIDTH = DIALOG_MIN_WIDTH_STANDARD + MEAS_LIB_ACTION_BUTTON_MIN_WIDTH
DIALOG_LIBRARY_EDIT_INIT_HEIGHT = DIALOG_MIN_HEIGHT_STANDARD * 2
REFDES_SCROLL_COMPACT_MAX_H = 64

# Chart measurement palette
CHART_PALETTE_VOLUME_FILL    = "#2563EB"
CHART_PALETTE_VOLUME_EDGE    = "#1D4ED8"
CHART_PALETTE_AREA_FILL      = "#F97316"
CHART_PALETTE_AREA_EDGE      = "#EA580C"
CHART_PALETTE_HEIGHT_FILL    = "#16A34A"
CHART_PALETTE_HEIGHT_EDGE    = "#166534"
CHART_PALETTE_OFFSET_X_FILL  = "#7C3AED"
CHART_PALETTE_OFFSET_X_EDGE  = "#6D28D9"
CHART_PALETTE_OFFSET_Y_FILL  = "#DB2777"
CHART_PALETTE_OFFSET_Y_EDGE  = "#BE185D"
CHART_PALETTE_OFFSET_R_FILL  = "#0891B2"
CHART_PALETTE_OFFSET_R_EDGE  = "#0E7490"
CHART_PALETTE_SOLDER_FILL    = "#DC2626"
CHART_PALETTE_SOLDER_EDGE    = "#991B1B"

# HTML/PPTX Report theme
RPT_DARK_BG           = BG_PRIMARY
RPT_DARK_BG_CODE      = BG_SECONDARY
RPT_DARK_TEXT         = TEXT_PRIMARY
RPT_DARK_BORDER       = BORDER
RPT_TEXT_BODY         = TEXT_PRIMARY
RPT_H1_COLOR          = TEXT_PRIMARY
RPT_H2_COLOR          = ACCENT_PRIMARY
RPT_ACCENT            = ACCENT_PRIMARY
RPT_BORDER            = BORDER_SUBTLE
RPT_SURFACE           = BG_SECONDARY
RPT_TEXT_MUTED        = TEXT_MUTED
RPT_SECTION_LABEL_BG  = PRIMARY_100
RPT_FOOTER_TEXT       = TEXT_DISABLED
RPT_ERROR_TEXT        = ACCENT_ERROR
RPT_BADGE_INFO_BG     = INFO_SURFACE
RPT_BADGE_SUCCESS_BG  = SUCCESS_SURFACE_SUBTLE
RPT_BADGE_WARNING_BG  = WARNING_SURFACE
RPT_BADGE_ERROR_BG    = ERROR_SURFACE
RPT_BADGE_NEUTRAL_BG  = NEUTRAL_SURFACE
RPT_CARD_INFO_BG      = INFO_SURFACE_SUBTLE
RPT_CARD_SUCCESS_BG   = SUCCESS_SURFACE_SUBTLE
RPT_CARD_WARNING_BG   = WARNING_SURFACE_SUBTLE
RPT_CARD_ERROR_BG     = ERROR_SURFACE_SUBTLE
RPT_TABLE_HEADER_BG   = RPT_SECTION_LABEL_BG
RPT_FONT_BODY_PX     = 13
RPT_FONT_LABEL_PX    = 12
RPT_FONT_FOOTER_PX   = 11

# Excel export palette (stored with #; exporters strip it for openpyxl)
EXCEL_HEADER_BG = PRIMARY_700
EXCEL_SECTION_BG = PRIMARY_500
EXCEL_HEADER_TEXT = TEXT_ON_ACCENT
EXCEL_SECTION_TEXT = TEXT_ON_ACCENT
EXCEL_LABEL_BG = BG_SECONDARY
EXCEL_VALUE_BG = BG_BLOCK
EXCEL_BORDER = BORDER
EXCEL_TEXT_PRIMARY = TEXT_PRIMARY
EXCEL_TEXT_MUTED = TEXT_SECONDARY

# Typography
FONT_FAMILY = "\"Noto Sans TC\", \"Microsoft JhengHei UI\", \"Microsoft JhengHei\", \"Microsoft YaHei UI\", \"Microsoft YaHei\", \"Segoe UI\", \"PingFang TC\", \"Source Han Sans TC\", Roboto, sans-serif"
FONT_FAMILY_MONO = "\"JetBrains Mono\", \"Cascadia Code\", \"Fira Code\", Consolas, \"Courier New\", monospace"
MAX_UI_FONT_PT = 18

FONT_SIZE_TITLE = 18.0
FONT_SIZE_SECTION = 12.0
FONT_SIZE_BODY = 10.0
FONT_SIZE_CAPTION = 9.0
FONT_SIZE_SMALL = 8.5
FONT_SIZE_TINY = 8.0
FONT_SIZE_MONO = 10.0
FONT_SIZE_PROCESS_DASH_KPI = 10.0
FONT_SIZE_PROCESS_DASH_KPI_MEDIUM = 10.0
FONT_SIZE_PROCESS_DASH_STAT = 10.0
FONT_SIZE_DASH_LABEL = 10.0
PROCESS_ALARM_CARD_BG_NORMAL   = "#E8F8EE"  # 淡綠（alarmTone=normal，與 ACCENT_SUCCESS 同色族）
PROCESS_ALARM_CARD_BG_WARNING  = "#FFF5E0"  # 淡琥珀（alarmTone=warning，與 ACCENT_WARNING 同色族）
PROCESS_ALARM_CARD_BG_CRITICAL = "#FFF0EE"  # 淡紅（alarmTone=critical，與 ACCENT_ERROR 同色族）
PROCESS_DASH_GRID_H_SPACING = 8
PROCESS_DASH_GRID_V_SPACING = 4
PROCESS_DASH_CARD_MARGIN = 8
PROCESS_DASH_SECTION_GAP = 10  # 稽核修正 D-01：6px → 10px，提升卡片分隔可視度

TYPO_APP_TITLE_PT = FONT_SIZE_TITLE
TYPO_PAGE_TITLE_PT = FONT_SIZE_TITLE
TYPO_SECTION_TITLE_PT = FONT_SIZE_SECTION

SIDEBAR_SECTION_TITLE_FONT_SIZE = 10.5
SIDEBAR_NAV_FONT_SIZE = 10
SIDEBAR_LABEL_FONT_SIZE = 9
SIDEBAR_PHASE_FONT_SIZE = 8.5
SIDEBAR_MICRO_FONT_SIZE = 7.5

DATA_SETUP_DENSE_STEP_TITLE_FONT_SIZE = FONT_SIZE_SECTION
DATA_SETUP_DENSE_CONTROL_FONT_SIZE = FONT_SIZE_BODY

FORM_PAGE_CONTENT_MAX_WIDTH = 960

FONT_WEIGHT_BOLD = 700
FONT_WEIGHT_SEMIBOLD = 600
FONT_WEIGHT_NORMAL = 400

# Backward-compat aliases
FONT_SIZE_PLACEHOLDER = FONT_SIZE_SMALL
FONT_SIZE_DISABLED = FONT_SIZE_SMALL
SIDEBAR_FONT_SIZE = SIDEBAR_LABEL_FONT_SIZE
SIDEBAR_CONTENT_FONT_SIZE = SIDEBAR_LABEL_FONT_SIZE
NAV_STEP_FONT_SIZE = SIDEBAR_NAV_FONT_SIZE
NAV_PHASE_HEADER_FONT_SIZE = SIDEBAR_PHASE_FONT_SIZE

# Control sizing tokens
LABEL_ROW_MIN_HEIGHT = 22
INPUT_MIN_HEIGHT = 30
SECTION_TITLE_MIN_HEIGHT = 28

# Page layout
PAGE_CONTENT_MARGIN = 16
PAGE_CONTENT_SPACING = 12
DATA_LIST_PAGE_MIN_WIDTH = 600
WINDOW_MIN_WIDTH = 800
WINDOW_MIN_HEIGHT = 640
WINDOW_GEOMETRY_VISIBLE_MARGIN = 16
